
CREATE TABLE IF NOT EXISTS insumos (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome TEXT NOT NULL CHECK(length(trim(nome)) BETWEEN 1 AND 80),
 especificacao TEXT NOT NULL DEFAULT '',
 categoria TEXT NOT NULL,
 unidade TEXT NOT NULL,
 saldo_milesimos BIGINT NOT NULL DEFAULT 0 CHECK(saldo_milesimos >= 0),
 versao INTEGER NOT NULL DEFAULT 1,
 criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
 atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS funcionarios (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome TEXT NOT NULL CHECK(length(trim(nome)) BETWEEN 1 AND 80),
 versao INTEGER NOT NULL DEFAULT 1,
 criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
 atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS obras (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome TEXT NOT NULL CHECK(length(trim(nome)) BETWEEN 1 AND 80),
 versao INTEGER NOT NULL DEFAULT 1,
 criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
 atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS administradores (
 usuario TEXT PRIMARY KEY,
 salt TEXT NOT NULL,
 senha_hash TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS retiradas (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 chave_requisicao TEXT NOT NULL UNIQUE,
 conteudo_hash TEXT NOT NULL,
 obra_id INTEGER REFERENCES obras(id) ON DELETE CASCADE,
 funcionario_id INTEGER REFERENCES funcionarios(id) ON DELETE SET NULL,
 obra_nome TEXT NOT NULL,
 funcionario_nome TEXT NOT NULL,
 criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS retirada_itens (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 retirada_id INTEGER NOT NULL REFERENCES retiradas(id) ON DELETE CASCADE,
 insumo_id INTEGER REFERENCES insumos(id) ON DELETE SET NULL,
 codigo TEXT NOT NULL,
 nome TEXT NOT NULL,
 especificacao TEXT NOT NULL,
 unidade TEXT NOT NULL,
 quantidade_milesimos BIGINT NOT NULL CHECK(quantidade_milesimos > 0)
);
CREATE INDEX IF NOT EXISTS idx_itens_retirada ON retirada_itens(retirada_id);
CREATE INDEX IF NOT EXISTS idx_itens_insumo ON retirada_itens(insumo_id);
CREATE INDEX IF NOT EXISTS idx_retirada_obra ON retiradas(obra_id);
CREATE INDEX IF NOT EXISTS idx_retirada_funcionario ON retiradas(funcionario_id);


CREATE TABLE IF NOT EXISTS sessoes_admin (token_hash TEXT PRIMARY KEY, expira_em TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_sessoes_expira ON sessoes_admin(expira_em);
CREATE TABLE IF NOT EXISTS tentativas_login (chave TEXT PRIMARY KEY, total INTEGER NOT NULL, expira_em TIMESTAMPTZ NOT NULL);

CREATE TABLE IF NOT EXISTS funcionario_pins (
 funcionario_id INTEGER PRIMARY KEY REFERENCES funcionarios(id) ON DELETE CASCADE,
 salt TEXT NOT NULL,
 pin_hash TEXT NOT NULL,
 tentativas INTEGER NOT NULL DEFAULT 0,
 bloqueado_ate BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS checklist_conta (usuario TEXT PRIMARY KEY, salt TEXT NOT NULL, senha_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS checklist_sessoes (token_hash TEXT PRIMARY KEY, ate BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS checklist_tentativas (chave TEXT PRIMARY KEY, total INTEGER NOT NULL, ate BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS checklist_ambientes (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 obra_id INTEGER NOT NULL REFERENCES obras(id) ON DELETE CASCADE,
 nome TEXT NOT NULL CHECK(length(trim(nome)) BETWEEN 1 AND 80),
 projeto INTEGER NOT NULL DEFAULT 0 CHECK(projeto IN (0,1)),
 conferencia INTEGER NOT NULL DEFAULT 0 CHECK(conferencia IN (0,1)),
 fita INTEGER NOT NULL DEFAULT 0 CHECK(fita IN (0,1)),
 exportacao INTEGER NOT NULL DEFAULT 0 CHECK(exportacao IN (0,1)),
 versao INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_checklist_obra ON checklist_ambientes(obra_id);

ALTER TABLE checklist_ambientes ADD COLUMN IF NOT EXISTS corte INTEGER NOT NULL DEFAULT 0 CHECK(corte IN (0,1));
ALTER TABLE checklist_ambientes ADD COLUMN IF NOT EXISTS producao INTEGER NOT NULL DEFAULT 0 CHECK(producao IN (0,1));
ALTER TABLE checklist_ambientes ADD COLUMN IF NOT EXISTS obra INTEGER NOT NULL DEFAULT 0 CHECK(obra IN (0,1));

DO $$
BEGIN
 IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='retiradas'::regclass AND conname='retiradas_obra_id_fkey' AND confdeltype<>'c') THEN
  ALTER TABLE retiradas DROP CONSTRAINT retiradas_obra_id_fkey;
  ALTER TABLE retiradas ADD CONSTRAINT retiradas_obra_id_fkey FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE;
 END IF;
END $$;
